### ISSUE TITLE
Unable to download package from maven

### ISSUE THREAD

**Issue by BaesKevin** [sventorben/keycloak-home-idp-discovery#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Maven can't resolve this package using the coordinates on this page https://github.com/sventorben/keycloak-home-idp-discovery/packages/1112199?version=19.1.0 

### Expected Behavior

Maven to be able to download this package

### Steps To Reproduce

1. add the folowing to pom.xml

        <dependency>
            <groupId>de.sventorben.keycloak</groupId>
            <artifactId>keycloak-home-idp-discovery</artifactId>
            <version>19.1.0</version>
        </dependency>

2. unable to resolve (happens with most recent version as well)

### Version

```markdown
- Keycloak: 19.0.3
- This extension: 19.1.0
```

**Comment by sventorben** [comment]
Closing this issue due to missing feedback.
