### ISSUE TITLE
[BUG] Labels shown in select login method menu are not user friendly

### ISSUE THREAD

**Issue by andsouto** [sventorben/keycloak-home-idp-discovery#125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I created a new authentication flow this way:

![Screenshot from 2022-12-20 13-50-09](https://user-images.githubusercontent.com/4125706/208695814-ee43e8fe-850c-45f4-8fa0-a9ce48940bd0.png)

This works as expected showing by default the standard username + password form and allows changing to use Home IdP Discovery using the "Try another way" link:

![Screenshot from 2022-12-20 13-49-55](https://user-images.githubusercontent.com/4125706/208696276-926ae158-9408-42c1-99fe-6eaf9ba160fd.png)

The problem is that when I click that link this is what I see:

![Screenshot from 2022-12-20 13-50-09](https://user-images.githubusercontent.com/4125706/208696401-dcd78f1d-c63c-4488-bd3e-896ae22e5060.png)

As you can see the first option includes a user friendly description but the second one not.

Are that strings "home-idp-discovery-display-name" and "home-idp-discovery-help-text" supposed to be customized by applying some configuration or is something missing in this project that needs to be addressed?

### Expected Behavior

Seeing a user friendly explanation like for the username and password option.

### Version

```markdown
- Keycloak: 20.0.2
- This extension: 20.0.1
```

**Comment by andsouto** [comment]
I think I find the solution by myself: "home-idp-discovery-display-name" and "home-idp-discovery-help-text" are just the translation strings and adding then in a `messages_xx.properties` of a custom theme replaces them with whatever you need. Feel free to close the issue and sorry for the noise. I hope it helps someone that encounters the same problem.

**Comment by sventorben** [comment]
Thanks for the hint. I will add this to the documentation.

**Comment by sventorben** [comment]
Added default messages in Englisch and German.
Also documented how to customize these messages.
