### ISSUE TITLE
[Feature] login_hint in url

### ISSUE THREAD

**Issue by brecht-vermeersch** [sventorben/keycloak-home-idp-discovery#154]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Is your feature related to a problem? Please describe.

When I enter my email, I get redirected to the idp. Here I have to enter my email again

### Describe the solution you'd like

Maybe add the login_hint query param with the already entered email

### Anything else?

Thx for the great work

**Comment by sventorben** [comment]
Hello @brecht-vermeersch 

which version do you use?
This should be supported since version 20.0.1 of this authenticator.

Regards
Sven-Torben

**Comment by brecht-vermeersch** [comment]
I am using 20.0.3. This morning I tried upgrading to 21 but I got an error (with a fresh install). Something to do with the theme

**Comment by brecht-vermeersch** [comment]
I am using auth0 as the idp

**Comment by sventorben** [comment]
> I am using auth0 as the idp

When Keycloak redirects to auth0, does the URL include the `login_hint` parameter or not?

**Comment by sventorben** [comment]
> This morning I tried upgrading to 21 but I got an error (with a fresh install). Something to do with the theme

Version 21.0.0 only works with Keycloak >= 20.0.0.
Which Keycloak version did you use and what was the exact error message?

**Comment by sventorben** [comment]
@brecht-vermeersch Please try version 21.0.1 - there was indeed an issue with the theme in version 21.0.0

**Comment by sventorben** [comment]
@brecht-vermeersch check the latest Keycloak release (21.0.1). The issue with the theme should be fixed (https://github.com/keycloak/keycloak/issues/17313)

**Comment by sventorben** [comment]
@brecht-vermeersch Does this work for you now?
