### ISSUE TITLE
[Feature] Automatically authenticate based on login_hint

### ISSUE THREAD

**Issue by benovie** [sventorben/keycloak-home-idp-discovery#161]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Is your feature related to a problem? Please describe.

in some cases we have applications that already ask a user for their e-mail address before forwarding them to our keycloak instance. 
We use the login_hint query param so that users don't have to fill in their e-mail address twice, but still they will see a login screen on which they need to submit their e-mail. 

### Describe the solution you'd like

it would be nice (I think) that the plugin just tries to authenticate based on the login_hint. 

For BC reasons it may be nice to create a setting for this
 - tryToAuthenticateBasedOnLoginHint (or something link that)

or maybe to allow an extra query param to enforce authenticating based on the login_hint

**Comment by sventorben** [comment]
Nice one, @benovie!
Do you want to give release 21.1.0 a try and see if it works for you?
https://github.com/sventorben/keycloak-home-idp-discovery/releases/tag/v21.1.0
