### ISSUE TITLE
[Feature] Support "Remember Me"

### ISSUE THREAD

**Issue by riccardomasini** [sventorben/keycloak-home-idp-discovery#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, i configured the Home IdP Discovery version 20.0.3 on a Keycloak 20.0.5 and works well, but the Remember Me flag doesn't work anymore. If i use the standard browser flow it works after browser restarting.
My custom flow with the Idp Discovery is a copy of the standard browser flow.

Thanks 
Riccardo

### Expected Behavior

I'm expecting that when i open again my browser, if the Remember Me session is not expired, i directly log in my application

### Steps To Reproduce

1) Configure Idp Discovery Flow
2) Enable Remeber Me flag in Realm Settings -> Login
3) Increase the SSO Remember Me Session
4) Log in with Keycloak with Remember Me flag active
5) Close Browser
6) Open Browser again and connect to the application. Keycloak need the login again

### Version

```markdown
- Keycloak:20.0.5
- This extension: 20.0.3
```

**Comment by sventorben** [comment]
@riccardomasini thanks for reporting this.

It's not really a bug from my point of view. Keycloak's default Identity Provider Redirector does not support this either.
But I can implement a solution with one of the next releases if needed. I already sketched a potential solution in #168.

Once I find some time to write some tests, I will release a new version.

**Comment by riccardomasini** [comment]
@sventorben Thanks a lot for your fast feedback.
