### ISSUE TITLE
[Feature] Multiple IDP on domain

### ISSUE THREAD

**Issue by SangI762** [sventorben/keycloak-home-idp-discovery#171]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Is your feature related to a problem? Please describe.

It's really rare case, but I have few clients and they have two IDP providers in the company. I love this extension, it's exactly what I wanted long time ago. 

### Describe the solution you'd like

So, as a user I'd like to choose IDP when domain has more than one IDP mapped. Is it possible? 

### Describe alternatives you've considered

I tried to use only one idp per domain and use `Identity Provider Redirector`, but the problem is that fallback idp should be different based on domain. So this doesn't work for me. 
I have a lot of companies (b2b clients) integrated in our Keycloak instance, that's why I'm requesting this feature.

**Comment by linasslepikas** [comment]
Same here, would be really great to have this feature.

**Comment by sventorben** [comment]
Hello @SangI762 and @linasslepikas,

I am not sure if I like to implement a feature like that. the whole purpose of this extension is to eliminate the need for users to manually choose an identity provider.

Isn't there any other information available that could be used for an automated decision? How do users currently decide which identity provider to use?

Regards
Sven-Torben

**Comment by sventorben** [comment]
@SangI762 @linasslepikas 
Can you please check if the implementation in #181 could work for you?

**Comment by linasslepikas** [comment]
Sorry for delay. Checking it.

**Comment by sventorben** [comment]
@linasslepikas Do you need a release for it or can you build it from the source?

**Comment by linasslepikas** [comment]
Release would be great!

**Comment by sventorben** [comment]
I just released [21.2.0](https://github.com/sventorben/keycloak-home-idp-discovery/releases/tag/v21.2.0) as a pre-release

**Comment by SangI762** [comment]
@sventorben That's amazing. Just tried your latest build and it works as I intended. One small detail, after extension update (setting `Forward to first matched IdP` was false). So I didn't change anything in my configuration, just added second idp to domain and it didn't work at first. Then I made setting true, saved, made false and here we're. Everything seems awesome now.
Thanks again, man!

**Comment by linasslepikas** [comment]
All good here. Thank you!

**Comment by sventorben** [comment]
> One small detail, after extension update (setting `Forward to first matched IdP` was false)

I think that is a bug where the admin console does not respect the default parameters, see https://github.com/keycloak/keycloak/issues/19852.

It should behave as if `Forward to first matched IdP` is switched on, if no explicit configuration is set, because of backwards compatibility.
