### ISSUE TITLE
Does not work with RedHat SSO 7.6

### ISSUE THREAD

**Issue by sookeke** [sventorben/keycloak-home-idp-discovery#173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An internal server error has occurred

### Expected Behavior

Log on theme does not display but 
![image](https://user-images.githubusercontent.com/76934070/226784188-09ca27c9-079d-4210-8f56-640e429f2199.png)

### Version

```markdown
- Keycloak:
- This extension:
```

**Comment by sventorben** [comment]
Hello @sookeke 

can you please provide some corresponding logs and let me know which version of this authenticator you are using.

Thanks
Sven-Torben

**Comment by sventorben** [comment]
Note for myself: according to https://access.redhat.com/articles/2342881 Red Hat SSO 7.6 uses Keycloak 18.0.6

**Comment by sventorben** [comment]
> can you please provide some corresponding logs and let me know which version of this authenticator you are using.

@sookeke Can you please provide some more details here?

**Comment by sventorben** [comment]
Closing due to missing feedback. Feel free to reopen with more details.
