### ISSUE TITLE
[BUG] Link "Try Another Way" is not shown on login page

### ISSUE THREAD

**Issue by ilyai** [sventorben/keycloak-home-idp-discovery#183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I open the Keycloak login page with the following link: `https://[KEYCLOAK HOST]/realms/[REALM]/protocol/openid-connect/auth?client_id=[CLIENT ID]&state=[...]&redirect_uri=[...]&response_type=code&scope=openid` there is no "Try Another Way" link in order to login normally instead of using SSO.

This is the snippet with this link from login page template of Keycloak:
```
<#if auth?has_content && auth.showTryAnotherWayLink()>
              <form id="kc-select-try-another-way-form" action="${url.loginAction}" method="post">
                  <div class="${properties.kcFormGroupClass!}">
                      <input type="hidden" name="tryAnotherWay" value="on"/>
                      <a href="#" id="try-another-way"
                         onclick="document.forms['kc-select-try-another-way-form'].submit();return false;">${msg("doTryA
notherWay")}</a>
                  </div>
              </form>
          </#if>
```

I suspect that the condition may be false but what's may be the reason and how this extension could be related?

### Expected Behavior

The "Try Another Way" link to be shown as described in the [readme](https://github.com/sventorben/keycloak-home-idp-discovery#customized-messages-for-select-login-options-dialog)

### Version

```markdown
- Keycloak: 19.0.1
- This extension: 18.0.0
```

### Anything else?

![image](https://user-images.githubusercontent.com/1911270/231979268-23441fa6-8a54-4438-b791-06115637c9da.png)
![image](https://user-images.githubusercontent.com/1911270/231980886-d4580043-897f-4eb3-afdf-1a1bc2df303c.png)

**Comment by sventorben** [comment]
Hello @ilyai,

I just tested this with the latest version and the link works as expected.
Would you mind sharing a screenshot of you flow, because whether there is another way to login or not is determined based on the flow configuration.

Thanks
Sven-Torben

**Comment by ilyai** [comment]
Hello @sventorben ,
Thanks for quick reply. Yep, do you mean this settings, right?

![image](https://user-images.githubusercontent.com/1911270/232091206-abe2c16a-1f64-41e1-af01-df6a1c543377.png)

**Comment by sventorben** [comment]
@ilyai, yes, thanks.

With that flow there is no alternative configured when the flow reaches the Home IdP Discovery authenticator.
When a user logs in for the first time, no cookie is present. Hence, the cookie authenticator cannot authenticate the user. The only alternative that is left then is the the Home IdP Discovery authenticator. When the login form is rendered, Keycloak knows that there is no alternative ("no other way") to login and Keycloak does not render the link in that case.

Try to add another sub-flow with a "Username Password Form" authenticator if you require default login with username password or configure the flow like this:

- Cookie (alternative)
- Identity Provider Redirector (disabled)
- Home IdP Discovery (alternative)
- Sub-Flow (alternative)
  - Username Password Form (required)

**Comment by ilyai** [comment]
@sventorben It's been fixed, you're right it was a configuration issue, not a bug. Thanks for help.
