### ISSUE TITLE
Automatically Set Existing User  with home idp discovery 

### ISSUE THREAD

**Issue by nitin-vavdiya** [sventorben/keycloak-home-idp-discovery#210]
Hey, 
How can I set the authentication flow to automatically set existing users without asking users to add existing accounts or review profiles?
Steps:
1. Create a user with email(abc@gmail.com) and set a password 
2. Login with email and password 
3. Add identity provider and set home identity discovery with email domain gmail.com
4. Try to log in with the same email(abc@gmail.com)

**Actual result:**
After adding an email, it is redirected to login with Google, and after successful login in to google it is asking the user to add an existing account or review profile like below:
![tst](https://github.com/sventorben/keycloak-home-idp-discovery/assets/45592624/c3603287-cd1c-4f4c-9f1d-905a9799be9b)

**Expected results**
After login with Google user should be set to existing user.

I sent the authentication flow as below and bind it with my public client, but it is not working.
![image](https://github.com/sventorben/keycloak-home-idp-discovery/assets/45592624/3014de09-ce77-42e7-9525-ed16a424c579)

Can you please help here how we can configure the authentication flow to achieve this kind of behavior?

**Comment by sventorben** [comment]
Hello @nitin-vavdiya 

you need to configure the `First Login Flow` accordingly. The Server Administration Guide has the details on how to handle your case. Please check the docs at https://www.keycloak.org/docs/latest/server_admin/#_identity_broker_first_login
