### ISSUE TITLE
[Feature] Support "Use SSO" button

### ISSUE THREAD

**Issue by derlin** [sventorben/keycloak-home-idp-discovery#231]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Is your feature related to a problem? Please describe.

Having a login page with only an email is more and more used, but not uniformly enjoyed by end users. An alternative is the use of a  3-steps process with the help of an "SSO" button. The idea would be to allow both flows: current and 3-steps.

### Describe the solution you'd like

More precisely, in the 3-steps process the sign in page would look like:

<img width="419" alt="image" src="https://github.com/sventorben/keycloak-home-idp-discovery/assets/5463445/bf1128f9-dadd-4192-9621-4c18b88123e9">

If the user clicks on "Use SSO", he is redirected to a form with only the email field available (same as what we do now).

Examples:
* https://prowritingaid.com/en/Account/Login2
* https://control.divio.com/
* https://sentry.io/auth/login/ (a bit different, but same idea)

### Describe alternatives you've considered

I am not sure it is feasible with the current implementation.

### Anything else?

Thanks for this amazing work.

**Comment by sventorben** [comment]
Hello @derlin! 

Thanks for your feature request.
I think there is a way do set this up with Keycloak and this extensions as is by using two realms.

In the first realm you set up identity providers for the social logins that you need and add an additional identity provider that redirects to the second Keycloak realm. Within the second realm you can the use this extensions to discovery the identity provider.

Would something like this work for you or do you see any additional requirements?

Best regards
Sven-Torben

**Comment by derlin** [comment]
Thank you for your help! The two workarounds are enough for now, closing the issue.
