### ISSUE TITLE
Google custom SAML app integration with Keycloak #14284

### ISSUE THREAD

**Issue by rabzu** [sventorben/keycloak-home-idp-discovery#242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to setup IdP initiated SSO with a Google Workspace app to work with Keycloak. Here's the description of the problem in details: https://stackoverflow.com/questions/73568876/google-custom-saml-app-integration-with-keycloak

I've tried contacting Google support but they didn't find any problems on their side.
I'm wondering if Keycloak 17 actually supports this?

Also this issue may be related: https://stackoverflow.com/questions/71545359/idp-initiated-sso-from-google-saml-with-keycloak-as-identity-broker

**Comment by sventorben** [comment]
@rabzu how is this problem related to this extension?

**Comment by rabzu** [comment]
You are correct, it's not related to the extension
