### ISSUE TITLE
[BUG] User enumeration possible ("Invalid username or password.")

### ISSUE THREAD

**Issue by awoimbee** [sventorben/keycloak-home-idp-discovery#285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With a very simple auth flow:
```
Home IdP Discovery   Alternative
Password Form        Alternative
```
When a user enters an unregistered email address, he immediately gets "Invalid username or password."
See in video:
[Screencast from 2023-12-12 01-04-02.webm](https://github.com/sventorben/keycloak-home-idp-discovery/assets/22431493/1215a5ed-a860-42ea-9ae2-dc9e90bbaaee)

### Expected Behavior

The best thing would be to use the `Username Password Form` with pre-filled username (and password if it got autofilled by a password manager) instead of using the `Password Form`.
Seems like it's currently possible with this auth flow:
```
Home IdP Discovery    Required
Generic subflow "sub"
  Username Password Flow    Required 
```
The issue then is that the username is not pre-filled:
![kc-idp-discovery-behavior](https://github.com/sventorben/keycloak-home-idp-discovery/assets/22431493/ddf9772d-0b07-4841-8c34-1e3dd48f5d77)

### Version

```markdown
- Keycloak: 22.0.4
- This extension: 22.0.0 (EDIT: NOT 22.1.0)
```

**Comment by sventorben** [comment]
Hello @awoimbee 

thanks for using my extension and taking the time to share this issue.

The extension will not work with the password form authenticator due to changes I needed to implement for #251.

Using the username password form should work, as you described.
I think that I implemented a test case in #251 to make sure the username will be prefilled.

Let me double check and get back to you with some details.

**Comment by awoimbee** [comment]
Hi,
I'm so sorry, I did not understand that #251 solved my issue and that I'm using the previous release, 22.0.0.
I should not be opening issues at 3am.
I'll post something here when I get it working !

**Comment by awoimbee** [comment]
> Using Keycloak 22.0.4

Was fixed in v22.1.0.

**Comment by pcMarcos** [comment]
> > Using Keycloak 22.0.4
> 
> Was fixed in v22.1.0.

That's odd, I updated now to 23.0.3 and I'm facing the same experience. 🤔

**Comment by sventorben** [comment]
https://github.com/user-attachments/assets/e5cd1325-e295-4c20-95a4-edab13726783

**Comment by pcMarcos** [comment]
thank you! I really appreciate your time and help. I downloaded the latest version with idp discovery and it's really working. I'll investigate my configuration here
