### ISSUE TITLE
[BUG] Restart login button doesn't work when there are two or more IDPs

### ISSUE THREAD

**Issue by SangI762** [sventorben/keycloak-home-idp-discovery#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In case you have two or more IDPs restart login button does nothing, just reloads the same page, but can't get to the first screen and change the email.

![Screenshot 2023-12-18 at 09 06 43](https://github.com/sventorben/keycloak-home-idp-discovery/assets/14075076/6f307ab6-6511-4c79-ab7b-859aa8a87a44)

### Expected Behavior

Login flow is restarted

### Steps To Reproduce

Setup two IDPs on the same domain and make sure forward to first matched idp is turned off.

### Version

```markdown
- Keycloak:22.0.3
- This extension: 
Manifest-Version: 1.0
Created-By: Maven JAR Plugin 3.3.0
Build-Jdk-Spec: 17
Implementation-Title: Keycloak: Home IdP Discovery
Implementation-Version: 22.0.0
Dependencies: org.keycloak.keycloak-services
Sealed: true
```

**Comment by sventorben** [comment]
Where does that restart login button come from? I am trying to reproduce this, but that button does not show up.

![image](https://github.com/sventorben/keycloak-home-idp-discovery/assets/12183470/f03a1a26-f03f-4ed1-a1fa-cd9b9df5dfa0)

Do you have a custom theme that adds the button?

**Comment by SangI762** [comment]
Hm, strange. No, I'm using default form. But maybe my auth flow makes that.
I'll test it more and come back.
![Uploading Screenshot 2023-12-19 at 09.48.30.png…]()

**Comment by SangI762** [comment]
Ok, found. If user (exact email) exist in realm then that button comes up. If not, then email neither button isn't shown on the form.

**Comment by sventorben** [comment]
So, everything ist ok or do you think this is a bug?

**Comment by SangI762** [comment]
I still think this is a bug. I need Bypass login page = true. Now I'm forced to turn this off to avoid this bug.

**Comment by sventorben** [comment]
Have you tried version 22.1.0 (https://github.com/sventorben/keycloak-home-idp-discovery/releases/tag/v22.1.0)?
Maybe it is fixed there, because of changes in the way the user is stored in the session.

**Comment by SangI762** [comment]
Will check that as well. Thanks.

**Comment by SangI762** [comment]
Tested v22.1 and behaviour is the same.

**Comment by SangI762** [comment]
Any plans to fix it?

**Comment by sventorben** [comment]
I have a PR, but need to do some additional tests whether this breaks any other needed behaviour. Automated tests looked good so far, though.

However, I am still not able to reproduce this in a way that the button on the IdP selection page is shown.

**Comment by SangI762** [comment]
@sventorben awesome! If you're able to make a jar with this fix - I can test it on my environment.
