### ISSUE TITLE
[Feature] login for user not linked to corporate IDP

### ISSUE THREAD

**Issue by simonpayne1** [sventorben/keycloak-home-idp-discovery#34]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Is your feature related to a problem? Please describe.

Hi - this module looks perfect for a requirement i have, however the difference being that some users who do not belong to a corporate SSO (with a known email domain) would still require authentication.

these users may have personal email addresses @gmail.com or @hotmail.com etc.

however, the business would still like to manage the user accounts.

### Describe the solution you'd like

I think that maybe you do not want the user to authenticate direct in the realm, as you have removed the password field.  

So a suggestion might be to have another realm as default - this realm can be configured for public registrations etc or as required by the business use case.

e.g.
  UserModel user = context.getUser();
  
  final Optional<IdentityProviderModel> homeIdp = discoverHomeIdp(context, user, username);
  
  if (homeIdp.isEmpty()) {
      new Redirector(context).redirectTo("a default realm");
  } else {
      new Redirector(context).redirectTo(homeIdp.get());
  }

### Anything else?

I'm happy to contribute to the effort :)

**Comment by sventorben** [comment]
Hello @simonpayne1,

thanks for this feature request.  It is not uncommon to redirect users to a central/default IdP in case no home IdP or realm could be determined. However, this is configurable within Keycloak by adding the `Identity Provider Redirector` as an alternative authenticator.

![image](https://user-images.githubusercontent.com/12183470/155400572-a0104039-9197-4971-b5fd-921ebb54f128.png)

Therefore, I would rather not implement this feature as part of this authenticator.

Best regards
Sven-Torben

**Comment by simonpayne1** [comment]
thanks for tip - i will try this

**Comment by egeorges92** [comment]
Thank you, Sven, for the quick answer.
I know and try before the Identity Provider Redirector. The issue with it, is that it doesn't sent the login_hint to the IdP, and it's an essential requirement for my use case.
