### ISSUE TITLE
[Bug] Forward login_hint for non-existent user with matching domain

### ISSUE THREAD

**Issue by jsedanoj** [sventorben/keycloak-home-idp-discovery#363]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Is your feature related to a problem? Please describe.

When I type the email in the HomeIdpDiscovery screen... it is lost when forwarded to the creen of the delegated IdP, so I need to type it again.

![image](https://github.com/sventorben/keycloak-home-idp-discovery/assets/12848713/5c7cb9b1-a8cb-45d8-936d-76ba74b697fd)

![image](https://github.com/sventorben/keycloak-home-idp-discovery/assets/12848713/157f556d-6d71-42ce-a8fd-4af0a2ac7c3e)

### Describe the solution you'd like

The email written by the user in the screen of HomeIdpDiscovery should be added to the login_hint of the delegated IdP.

### Describe alternatives you've considered

To make it clear, I do not talking about this:

![image](https://github.com/sventorben/keycloak-home-idp-discovery/assets/12848713/5c161361-1fd5-4ff1-b285-f662068e6697)

I do not mean copying the email from the client application into the broker, but copying the email from the broker into the delegated IdP.

**Comment by sventorben** [comment]
Hey @jsedanoj 

Keycloak should take care of this already. Have you switched on the "Pass login_hint" advanced setting in your identity provider configuration?

Best,
Sven-Torben

**Comment by sventorben** [comment]
This looks like a bug within my extension. I will fix this with the next release.
