### ISSUE TITLE
[BUG] Forward login_hint to Identity Provider "microsoft" not works

### ISSUE THREAD

**Issue by aradmueller** [sventorben/keycloak-home-idp-discovery#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I understood the function "Bypass login page" so that the entered user name is forwarded to the identity provider (in my case "microsoft"). I tested the new version 24.1.0, because I waited for the fix https://github.com/sventorben/keycloak-home-idp-discovery/issues/363.
When I look at the web request which is called, I don't see any parameter "login_hint" (same with version 24.0.0):
```
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?scope=User.read&state=xxx&response_type=code&client_id=guid&redirect_uri=https%3A%2F%2Flocalhost
```

### Expected Behavior

If I manually add login_hint to the URL called (@ must be rewritten as %40), the user name is taken over correctly:
```
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?scope=User.read&state=xxx&response_type=code&client_id=guid&redirect_uri=https%3A%2F%2Flocalhost&login_hint=test%40test.onmicrosoft.com
```

### Version

```markdown
- Keycloak: 24.1.0
```

### Anything else?

the setting as described here  https://github.com/sventorben/keycloak-home-idp-discovery/issues/363#issuecomment-2106312028 does not exist with the identity provider "microsoft":
![image](https://github.com/sventorben/keycloak-home-idp-discovery/assets/26752704/b2873db8-0eaf-4a32-b08b-585e5e54bdd6)

**Comment by sventorben** [comment]
Hey @aradmueller 

you stumbled upon a specific problem with the microsoft provider. As you stated, it does not have the "pass login_hint" parameter  shown in the frontend, but it exists backend-wise. So, the default value for the parameter is always false and then Keycloak does not attach the login_hint query parameter to the URLs. This needs to be fixed/support by Keycloak and cannot be fixed within this extension. There is a similiar issue already -> https://github.com/keycloak/keycloak/issues/12864#issuecomment-1175219193

Please file an issue or feature request with the Keycloak project, if you really need this.

Best,
Sven-Torben
