### ISSUE TITLE
Authenticator does not show in 

### ISSUE THREAD

**Issue by 1-alex98** [sventorben/keycloak-home-idp-discovery#38]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Everything works normally. I can set domains on idps, show them using the extra theme. All good.

I want to enable the authenticator but it is not shown in the Admin Console. 
![Screenshot_20220301_195501](https://user-images.githubusercontent.com/19996713/156231328-f98bca7c-de23-4696-a948-40da59949f77.png)

> If this authenticator gets configured as part of a browser based login flow

Makes me expect I can find it there and set it to required...

### Expected Behavior

authenticator is shown in the list of authenticators

### Steps To Reproduce

Nothing special here

### Version

```markdown
- Keycloak:16.1.1 (updating to 17.0.0 could be hard)
- This extension: Tried 17.0.1 and 16.0.0
```

### Anything else?

Some warnings in log:
```
ef_docker-keycloak-1  | 18:31:51,529 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-5) WFLYSRV0018: Deployment "deployment.keycloak-home-idp-discovery.jar" is using a private module ("org.keycloak.keycloak-services") which may be changed or removed in future versions without notice.
ef_docker-keycloak-1  | 18:31:52,476 WARN  [org.jboss.weld.Bootstrap] (Weld Thread Pool -- 8) WELD-000167: Class de.sventorben.keycloak.authentication.hidpd.HomeIdpDiscoveryRealmResource$MyAdminRoot is annotated with @RequestScoped but it does not declare an appropriate constructor therefore is not registered as a bean!
ef_docker-keycloak-1  | 18:31:57,677 WARN  [org.keycloak.services] (ServerService Thread Pool -- 65) KC-SERVICES0047: home-idp-discovery (de.sventorben.keycloak.authentication.hidpd.HomeIdpDiscoveryRealmResourceProviderFactory) is implementing the internal SPI realm-restapi-extension. This SPI is internal and may change without notice
```
None of those seem to be relevant.

The jar seems to be loaded correctly. (Screenshots shows custom build)
![Screenshot_20220301_194836](https://user-images.githubusercontent.com/19996713/156230466-7aafaa1b-96ce-41e2-bf13-69ca4128e5d5.png)

Have you got any ideas what cloud cause this? Are all authenticators always shown in that list/configuration UI? Did I missunderstand that the authenticator would show up in the ui?

**Comment by 1-alex98** [comment]
Tried keycloak 16.0.0 as well

**Comment by sventorben** [comment]
Hello @1-alex98,

> Makes me expect I can find it there and set it to required...

Yes, you can find it in the authenticator list, but not in the default browser flow as you are expecting.
Keycloak does not allow you to modify the default browser flow. You will have to create a copy of that flow (or create a new one).

![image](https://user-images.githubusercontent.com/12183470/156233546-82f4b1a4-29bd-4949-9fce-5a419f4a5900.png)

After you have copied the flow, you can add the authenticator to the copied flow by clicking on `Add Execution`

![image](https://user-images.githubusercontent.com/12183470/156233712-3513acd4-9f5f-4d0e-9822-2aadc9f0011b.png)

![image](https://user-images.githubusercontent.com/12183470/156233866-bda5c3f3-f38d-4688-9520-d83fbb791f49.png)

After adding the execution it should show up in your flow like this
![image](https://user-images.githubusercontent.com/12183470/156234014-53f86724-df3a-4c45-9fe2-edeb6f686796.png)

You can now change priority or requirements to your needs. Once that is done, you need to bind the flow accordingly either on a per client basis or for the realm.

![image](https://user-images.githubusercontent.com/12183470/156234281-81701ce1-6882-4049-a9e1-ac8028bb05c5.png)

For further details you may want to check the _Authentication flows_ section in the [user guide](https://www.keycloak.org/docs/17.0/server_admin/index.html#_authentication-flows).

Regards
Sven-Torben

**Comment by 1-alex98** [comment]
thank you very much
