### ISSUE TITLE
Passoword screen not coming if the user domain does not match with any of the condigured IDPs

### ISSUE THREAD

**Issue by manishchoudhary7496** [sventorben/keycloak-home-idp-discovery#381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using User federation (DB and LDAP both).
Now when i provide abc@example.com as user it is correctly redirecting me to the configured IDP.
But when i am entering other LDAP/DB user username : abc@demo.com its not showing me the password screen at all.

### Expected Behavior

Password screen should be there if the user email does not match with any of the IDPs configured domain.

### Version

```markdown
- Keycloak: 23.0.6
- This extension: 23.0.0
```

**Comment by sventorben** [comment]
@manishchoudhary7496 can you please provide your flow configuration - screenshot or realm export.

**Comment by manishchoudhary7496** [comment]
Hi @sventorben 
thank you for your reply.

Here is my flow configuration :

![Uploading Config.PNG…]()

**Comment by manishchoudhary7496** [comment]
Hi @sventorben
thank you for your reply.

Here is my flow configuration :
<img width="672" alt="Config" src="https://github.com/sventorben/keycloak-home-idp-discovery/assets/52537508/ae9ffdff-9e95-4e68-8b2a-ef614db05f54">

**Comment by manishchoudhary7496** [comment]
Hi @sventorben 
Please let me know if you need anything else
I would really appreciate your time

Thank You

**Comment by sventorben** [comment]
The configuration that you have seen in the video may be outdated. Please check the docs at https://sventorben.github.io/keycloak-home-idp-discovery/configuration.html and try to configure it as seen in the screenshot.

**Comment by manishchoudhary7496** [comment]
Hi @sventorben 
Thank you so much for explaining the same.

It is working as expected.

Thank You
