### ISSUE TITLE
[Feature] Add default Idp to switch to when domain not found within email domains from IdP

### ISSUE THREAD

**Issue by egeorges92** [sventorben/keycloak-home-idp-discovery#397]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Is your feature related to a problem? Please describe.

The goal is to set a default IdP in case no IDPs respond to the user's email domain.

### Describe the solution you'd like

PR to follow

**Comment by egeorges92** [comment]
https://github.com/sventorben/keycloak-home-idp-discovery/pull/398

**Comment by sventorben** [comment]
Closing this in favor of #401 as an outcome of discussion https://github.com/sventorben/keycloak-home-idp-discovery/discussions/396#discussioncomment-10066716
