### ISSUE TITLE
[Feature] Forward login_hint to default Identity Provider Redirector

### ISSUE THREAD

**Issue by sventorben** [sventorben/keycloak-home-idp-discovery#401]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Is your feature related to a problem? Please describe.

Given no home IdP could be found but a default home IdP is configured via Keycloak built-in Identity Provider Redirector, the username should be forwarded as a login_hint to the default IdP.

**Comment by Guite** [comment]
Any chance to release a patch update? We would like to try out that bugfix with KC 25.

**Comment by sventorben** [comment]
Sure! Try https://github.com/sventorben/keycloak-home-idp-discovery/releases/tag/v25.0.1

**Comment by Guite** [comment]
Thank you very much for the quick reaction. Works perfectly :+1:
