### ISSUE TITLE
[BUG] login_hint is passed incorrectly.

### ISSUE THREAD

**Issue by Dr0na** [sventorben/keycloak-home-idp-discovery#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When users are redirected to the linked Identity Provider (IdP) from a client that supports the login_hint parameter, the login hint currently being passed is missing the email domain. 

### Expected Behavior

The expected behavior is that the complete email address, including the domain, should be passed. A better solution might be to make this behavior configurable.

### Steps To Reproduce

1. Set up SSO for an Identity Provider.
2. Enable the provider to pass the login_hint parameter.
3. Go to the login page and enter the email address configured for SSO.
4. Click Sign In and capture the HTTP requests as you are redirected to the IdP's SSO page.
5. Inspect the login_hint parameter in the requests. You'll notice that it lacks the email domain, which prevents the SSO page from automatically populating the email field.

### Version

```markdown
- Keycloak: 25.0.1
- This extension: 25.0.0
```

**Comment by sventorben** [comment]
Hey @Dr0na 

is this happening every time or does this behavior change after the first login. 

Can you please check the identity provider links for the user after the first login of a user? What is the username at the identity provider shown there?

**Comment by Dr0na** [comment]
Hey @sventorben 
   
Just noticed that it doesn't with Okta but works with JumpCloud. I believe it must be some config issue unrelated to this authenticator. Should be good to close it.

**Comment by sventorben** [comment]
It may be due to the username (subject claim) send by the IdP upon first login.

**Comment by Dr0na** [comment]
@sventorben I think you are right!
