### ISSUE TITLE
[Feature] Show IdP selection also when only one IdP matches

### ISSUE THREAD

**Issue by lukas-r** [sventorben/keycloak-home-idp-discovery#469]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Is your feature related to a problem? Please describe.

Right now, if multiple IdPs match a domain and `Forward to first matched IdP` is disabled, the list of matching IdPs is shown. If only one IdP matches, an automatic redirect happens. This redirect can be unexpected for the user, because there is now hint for him that Keycloak is gonna redirect to another IdP.

### Describe the solution you'd like

Add a config option that allows showing the IdP selection page, even when only one IdP matches. This way, the user will need to explicitly have to click on a button to identify via the external IdP and the redirect will not be unexpected. This can be considered a UX improvement (even though an extra step of clicking the IdP button is introduced).

**Comment by sventorben** [comment]
Thank you, @lukas-r, for your feature request and for taking the time to describe your use case.

However, the purpose of this extension is specifically to avoid requiring users to click any buttons and to streamline the redirection process. Introducing an additional step, such as displaying the IdP selection page when only one IdP matches, goes against the core intent of this extension.

For this reason, I will not be implementing the requested feature. I appreciate your understanding, and I encourage you to explore other solutions or customizations that may better suit your needs.

Thank you for your feedback and for using the extension!
