### ISSUE TITLE
404 when trying to configure a domain - keycloak 17.0.1 or 18.0.0 w/quarkus?

### ISSUE THREAD

**Issue by knuto** [sventorben/keycloak-home-idp-discovery#56]
Hi, thanks for putting this out here - it seems to be just what I need, but unfortunately I am not able to get it to work:

I put the keycloak-home-idp-discovery.jar file into /opt/keycloak/providers 
(using a docker image build for this, based on quay.io/keycloak/keycloak:version)
As expected a choice for 'home-idp-discovery' is available and I configure it.
No 'Home Idp Discovery" tab shows up for any providers (maybe this is because no domains have been configured yet?)

Then (maybe I am missing something obvious?)  when trying to use the admin API to add some domains to an identity provider,

PUT https://admin:8443/admin/realms/myrealm/identity-provider/instances/google
payload = {
    "config": {
        "home.idp.discovery.domains": domain_list
    }
}

I just get 404's . (It wasn't entirely clear to me whether the config needs to be complete with client_id and secret etc, or if only "home.idp.discovery.domains" can be specified without overwriting the rest, but I have tried both without success)

I have added some logging and I see that  it seems that no instance of HomeIdpDiscoveryRealmResource is created.
(I am able to use GET with the same URL, but the GET endpoint in HomeIdpDiscoveryRealmResource is not called)
(while I observe that HomeIdpDiscoveryRealmResourceProviderFactory gets instantiated)
Any hints for further debugging/resolving this appreciated!

**Comment by sventorben** [comment]
Hey @knuto

the "Home IdP Discovery" tab should show up after enabling the "home-idp-discovery" theme under `Realm settings` -> `Themes` -> `Admin Console Theme`. Make sure you do this on the realm that you have used to login and to refresh the browser.

For the 404 it's tough to say what is going wrong. Maybe a stupid question, but did you add the identity provider with alias `google`?

**Comment by knuto** [comment]
Yes, this is just a google 'social' login provider definition

**Comment by knuto** [comment]
Ah - it seems I had added the theme for the same realm as the one I wanted to add domains to while being logged in
to the master realm. Once I added the theme to the master realm, I see the extra tab.
And I was able to PUT a config back in when using a copy of everything read from a GET + secret and domain list as well.
I still don't see any log from HomeIdpDiscoveryRealmResource PUT or GET in keycloak, but maybe the kubernetes log only shows stuff from the master realm, as I could now observe the GET call from the admin GUI.

Thanks!

**Comment by sventorben** [comment]
Could you try something like this, please?

```shell
USER=admin
PASS=admin
ACCESS_TOKEN=`curl -s --data "grant_type=password&client_id=admin-cli&username=${USER}&password=${PASS}" http://localhost:8080/realms/master/protocol/openid-connect/token | jq -r .access_token`
curl -H "Authorization: Bearer $ACCESS_TOKEN" http://localhost:8080/admin/realms/test-realm/identity-provider/instances/keycloak-oidc | jq --arg domains "example.com##example.org" '.config."home.idp.discovery.domains" = $domains'
```

**Comment by knuto** [comment]
I tried something analogue to the script above - and that works!
The difference to my API code is that in that code I use a client with admin privs within the target realm and not the master realm, as in your example.
