### ISSUE TITLE
why do you use Keycloak[Feature] <title>

### ISSUE THREAD

**Issue by HelloTo4x** [sventorben/keycloak-home-idp-discovery#71]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Is your feature related to a problem? Please describe.

Hi, can u tell me why u use Keycloak instead of Spring security, which feature does it have but Spring security doesn't have it ?

**Comment by sventorben** [comment]
Spring Security is a customizable authentication and access-control framework. I use it as well. But if you want to use Spring Security with OIDC for example, you will need an identity provider. This is what Keycloak is good for - it's an identity provider.
So, it's not either or, it's both.

remark: This is an issue tracker for an open source Keycloak extension and not a forum for discussions or general questions. Please use the Spring or Keycloak mailing lists for questions related to the products.
