### ISSUE TITLE
Discovery based on full email addresses (localpart+domainpart)

### ISSUE THREAD

**Issue by nikzen** [sventorben/keycloak-home-idp-discovery#77]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Is your feature related to a problem? Please describe.

We are providing decentralised servers to our customers. One pain point is that our customer needs to know the domain to connect. We are looking into options of how to solve this user-flow problem. One idea is to provide a central keycloak idp the app will always use to ask for the correct domain. By using your great package this is seems to be partly solved, as the user will enter their corporate-email and then gets redirected to the correct idp/realm to connect if the domain like @corporate.com is correct.

Hoewever, we also have users who are using email addresses with domains like xyq@gmail.com. At this stage the routing will not work, as there would be more than one idp with @gmail.com domain.

### Describe the solution you'd like

Is it possible to add full email addresses to the idp discovery, so that 
- user1@gmail.com gets routed to teamofuser1.idp.example.com
- user2@gmail.com gets routed to teamofuser2.idp.example.com

Thanks a lot for your help

**Comment by sventorben** [comment]
Hello @nikzen,

thanks for this feature request. Have you tried Keycloak's default feature for linking users to IdPs?
My authenticators supports this out of the box. 

You can try the following:

1.  Switch on the `Forward to linked IdP` feature in the authenticator config
2. Add the email address to the user ![image](https://user-images.githubusercontent.com/12183470/176899667-21224baf-5461-4a39-81ac-5ccbfb6f5995.png)
3. Add an identity provider link to the IdP (e.g. teamofuser1.idp.example.com)  ![image](https://user-images.githubusercontent.com/12183470/176899923-66cfdfaf-ff4e-4294-bcef-c4cfbc5771c4.png)

With this configuration the authenticator will prefer the linked IdP over the IdP configured for the domain.
Please, let me know if this works for you.

Regards
Sven-Torben

**Comment by sventorben** [comment]
@nikzen Does this work for you?

**Comment by sventorben** [comment]
Closing this issue due to missing feedback.
